name: Main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v1.1.0

      - name: Build
        run: pnpm -- lerna run --stream build

      - name: Lint
        run: pnpm -- lerna run --parallel lint

      - name: Test
        run: pnpm -- lerna run --parallel test:coverage

      - name: Codecov js
        uses: codecov/codecov-action@v2
        with:
          flags: js
          directory: ./packages/js

      - name: Codecov browser
        uses: codecov/codecov-action@v2
        with:
          flags: browser
          directory: ./packages/browser
