name: Main

on:
  push:
    branches:
      - master
      - 'push-action/**'
  pull_request:

concurrency:
  group: main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node and pnpm
        uses: silverhand-io/actions-node-pnpm-run-steps@v3

      - name: Build
        run: pnpm -r build

      - name: Lint
        run: pnpm -r lint

      - name: Test
        run: pnpm -r test:coverage

      - name: Codecov js
        uses: codecov/codecov-action@v3
        with:
          flags: js
          directory: ./packages/js

      - name: Codecov browser
        uses: codecov/codecov-action@v3
        with:
          flags: browser
          directory: ./packages/browser
